# Generated by Django 5.0.2 on 2024-02-26 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_produitnc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitnc',
            name='id',
        ),
        migrations.AddField(
            model_name='produitnc',
            name='produit_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='magasin.produit'),
            preserve_default=False,
        ),
    ]
